---
title: "Question 3"
author: "Maryam Imani" , "Azadeh Samadian"
date: "December 1, 2018"
output: html_document
---


```{r , echo=TRUE}
#### Network Table
network <- read.table("token/networkomisegoTX.txt", header=FALSE, 
  	sep=" ",  col.names= c("fromNodeID", "toNodeID", "unixTime", "tokenAmount"), colClasses=c('factor', 'factor', 'numeric', 'numeric') )

library(anytime)
network$newDate <- anydate(network$unixTime)
network$newDate <- as.double(network$newDate)
network <- network[order(network$newDate , decreasing = FALSE),]  # Sorting based on Date
networkDF <- as.data.frame.matrix(network) 
head(network)
```

```{r , echo=TRUE}
#### Price Table 
Price <- read.table("tokenPrices/OMISEGO", header=TRUE, 
  	sep="\t",  col.names= c("Date",	"Open",	"High"	,"Low"	,"Close",	"Volume",	"MarketCap"), colClasses=c('factor', 'numeric', 'numeric','numeric', 'numeric', 'numeric', 'numeric') )
Price$newDate <- as.Date(strptime(x = as.character(Price$Date), format = "%m/%d/%Y"))
Price <- Price[order(Price$newDate, decreasing = FALSE),  ]  # Sorting based on Date
priceDF <- as.data.frame.matrix(Price) 
head(priceDF)

```

# Outlier

```{r , echo=TRUE}
maxTotalSupply<-140245398
subUnit<-10^18
outlier_value <- maxTotalSupply*subUnit
outlierData <- network [which(network$tokenAmount > outlier_value),]
#outlierData2 <- network [which(network$tokenAmount < 1.0e+16),]
#head(outlierData)
#library("dplyr")
#filter(mydata, tokenAmount < outlier_value)
message("Total Number of Outliers: ", length(outlierData$tokenAmount) )
```

## Remove outliers:
```{r , echo=TRUE}
withoutOutlierData <- network [which(network$tokenAmount < outlier_value),]
withoutOutlierData <- withoutOutlierData [which(withoutOutlierData$tokenAmount > 1.000000e+17),]

cleanNetworkDF <- as.data.frame.matrix(withoutOutlierData) 
```


## Feature Engineering
```{r , echo=TRUE}
### Creating a data frame with date and price return values 

priceReturn <- c()
priceReturn[1] <- 0

transNum <- c()
transNum[1] <- priceDF[1, 'newDate']

transFreqDF <- data.frame(table(cleanNetworkDF$newDate))
colnames(transFreqDF) <- c("newDate", "Freq")

for (t in 2:nrow(priceDF)) {
  
  # Finding price return in date t
  priceReturn[t] <- (priceDF[t, 'Close'] -  priceDF[t-1 ,'Close'] ) /  priceDF[t-1, 'Close'] 
  

  # Counting the number of date or #transaction per date
  transaction <- transFreqDF[transFreqDF$newDate == priceDF[t, 'newDate'], "Freq" ]
  
  if (is.na(transaction[1])) {
    transNum[t] <- 0
  } else {
    transNum[t] <- sqrt(transaction[1] )
  }
  
}


investorPerc <- c()
investorPerc[1] <- 0

sellerPerc <- c()
sellerPerc[1] <- 0

uniqueInvestor <- c()
uniqueInvestor[1] <- 0 

uniqueSeller <- c()
uniqueSeller[1] <- 0 

buyerSellerRatio <-c()

for (t in 2:nrow(priceDF) ){
  
    #### Counting the number of investors with more than 10 transaction 
  df <- subset(cleanNetworkDF, cleanNetworkDF$newDate == priceDF[t, 'newDate'] ) #, select=c(newDate)
  investorFreqDF <- data.frame(table(df$toNodeID))
  colnames(transFreqDF) <- c("Investor", "Freq")
  
  uniqueInvestor[t] = nrow(investorFreqDF)
  investorFreq <- investorFreqDF[investorFreqDF$Freq >10 , "Freq" ]
  
  if ( uniqueInvestor[t] == 0) {
    investorPerc[t] <- 0
  } else {
    investorPerc[t] <- length(investorFreq) / uniqueInvestor[t]
  }
  
  
  #### Counting the number of sellers with more than 10 transaction 
  sellerFreqDF <- data.frame(table(df$fromNodeID))
  #colnames(sellerFreqDF) <- c("Seller", "Freq")
  
  uniqueSeller[t] = nrow(sellerFreqDF)
  sellerFreq <- sellerFreqDF[sellerFreqDF$Freq >20 , "Freq" ]
  
  if ( uniqueSeller[t] == 0) {
    sellerPerc[t] <- 0
  } else {
    sellerPerc[t] <- length(sellerFreq) / uniqueSeller[t]
  }
  
  buyerSellerRatio[t] <- uniqueInvestor[t] / uniqueSeller[t]
  
}

mergeDF = data.frame( priceDF$newDate , priceReturn, transNum, investorPerc, sellerPerc, uniqueInvestor, uniqueSeller, buyerSellerRatio) 
colnames(mergeDF) <- c("newDate", "priceReturn", "transNum", "investorPerc", "sellerPerc", "uniqueInvestor", "uniqueSeller" , "buyerSellerRatio")

mergeDF <- mergeDF[-1, ]
head(mergeDF)
```


## Regression Model  (Multiple Linear Regression)
```{r , echo=TRUE} 

model <- lm(mergeDF$priceReturn ~ mergeDF$transNum + mergeDF$investorPerc + mergeDF$sellerPerc + mergeDF$uniqueInvestor + mergeDF$uniqueSeller + mergeDF$buyerSellerRatio , data = mergeDF)
summary(model)

# we can see that investorPerchas significant impact on the price return, so we will exclude the rest of features in the next experiment

``` 


```{r , echo=TRUE} 

model <- lm(mergeDF$priceReturn ~ mergeDF$investorPerc , data = mergeDF)
summary(model)

``` 


```{r , echo=TRUE} 
lm(mergeDF$priceReturn ~ mergeDF$investorPerc , data = mergeDF)
plot(mergeDF$priceReturn ~ mergeDF$investorPerc)

abline(-0.005883, 3.952442)
abline(lm(mergeDF$priceReturn ~ mergeDF$investorPerc))

``` 


## Feature Engineering
```{r , echo=TRUE}
### Creating a data frame with date and price return values 

priceReturn <- c()
priceReturn[1] <- 0

transNum <- c()
transNum[1] <- priceDF[1, 'newDate']

transFreqDF <- data.frame(table(cleanNetworkDF$newDate))
colnames(transFreqDF) <- c("newDate", "Freq")


cleanNetworkDF <- subset(cleanNetworkDF, cleanNetworkDF$tokenAmount < 1.00000006845609e+20 )

for (t in 2:nrow(priceDF)) {
  
  # Finding price return in date t
  priceReturn[t] <- (priceDF[t, 'Close'] -  priceDF[t-1 ,'Close'] ) /  priceDF[t-1, 'Close'] 
  

  # Counting the number of date or #transaction per date
  transaction <- transFreqDF[transFreqDF$newDate == priceDF[t, 'newDate'], "Freq" ]
  
  if (is.na(transaction[1])) {
    transNum[t] <- 0
  } else {
    transNum[t] <- sqrt(transaction[1] )
  }
  
}


investorPerc <- c()
investorPerc[1] <- 0

sellerPerc <- c()
sellerPerc[1] <- 0

uniqueInvestor <- c()
uniqueInvestor[1] <- 0 

uniqueSeller <- c()
uniqueSeller[1] <- 0 

buyerSellerRatio <-c()



for (t in 2:nrow(priceDF) ){
  
    #### Counting the number of investors with more than 10 transaction 
  df <- subset(cleanNetworkDF, cleanNetworkDF$newDate == priceDF[t, 'newDate'] ) #, select=c(newDate)
  investorFreqDF <- data.frame(table(df$toNodeID))
  colnames(transFreqDF) <- c("Investor", "Freq")
  
  uniqueInvestor[t] = nrow(investorFreqDF)
  investorFreq <- investorFreqDF[investorFreqDF$Freq >10 , "Freq" ]
  
  if ( uniqueInvestor[t] == 0) {
    investorPerc[t] <- 0
  } else {
    investorPerc[t] <- length(investorFreq) / uniqueInvestor[t]
  }
  
  
  #### Counting the number of sellers with more than 10 transaction 
  sellerFreqDF <- data.frame(table(df$fromNodeID))
  #colnames(sellerFreqDF) <- c("Seller", "Freq")
  
  uniqueSeller[t] = nrow(sellerFreqDF)
  sellerFreq <- sellerFreqDF[sellerFreqDF$Freq >20 , "Freq" ]
  
  if ( uniqueSeller[t] == 0) {
    sellerPerc[t] <- 0
  } else {
    sellerPerc[t] <- length(sellerFreq) / uniqueSeller[t]
  }
  
  buyerSellerRatio[t] <- uniqueInvestor[t] / uniqueSeller[t]
  
}

mergeDF = data.frame( priceDF$newDate , priceReturn, transNum, investorPerc, sellerPerc, uniqueInvestor, uniqueSeller, buyerSellerRatio) 
colnames(mergeDF) <- c("newDate", "priceReturn", "transNum", "investorPerc", "sellerPerc", "uniqueInvestor", "uniqueSeller" , "buyerSellerRatio")

mergeDF <- mergeDF[-1, ]
head(mergeDF)
```


## Regression Model  (Multiple Linear Regression)
```{r , echo=TRUE} 

model <- lm(mergeDF$priceReturn ~ mergeDF$transNum + mergeDF$investorPerc + mergeDF$sellerPerc + mergeDF$uniqueInvestor + mergeDF$uniqueSeller , data = mergeDF)
summary(model)

# we can see that investorPerchas significant impact on the price return, so we will exclude the rest of features in the next experiment

``` 


```{r , echo=TRUE} 

model <- lm(mergeDF$priceReturn ~ mergeDF$uniqueSeller , data = mergeDF)
summary(model)

``` 


```{r , echo=TRUE} 
lm(mergeDF$priceReturn ~ mergeDF$uniqueSeller , data = mergeDF)
plot(mergeDF$priceReturn ~ mergeDF$uniqueSeller)

abline(-0.005883, 3.952442)
abline(lm(mergeDF$priceReturn ~ mergeDF$uniqueSeller))

``` 
